In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
x=np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
x1=np.mean(x)
x1

5.5

In [8]:
x2=np.median(x)
x2

5.5

In [11]:
x=np.append(x,25)

In [13]:

x1=np.mean(x)
print(x1)
x2=np.median(x)
print(x2)

7.2727272727272725
6.0


In [14]:
# standard devation
x3=np.std(x)
x3

6.239039977008542

In [15]:
arr=np.arange(1,201)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [21]:
np.percentile(arr,99)

198.01

In [33]:
arrseed=np.random.seed(4)
arr100=np.random.randint(1,50,100)
arr100

array([47,  6,  2, 41, 24,  9, 10, 40, 46, 31, 41, 37, 45, 39, 43,  4,  1,
       22, 22, 10, 39, 39,  3, 47, 31,  9,  3, 24, 33, 41, 43, 46, 34, 33,
       46, 29,  4, 16, 35, 32, 18, 49, 18, 26, 10, 49, 13, 24, 31, 23,  4,
       12, 24,  7, 40, 46, 43,  8, 10, 19, 49, 22, 31, 16, 37, 28, 44,  9,
       38,  9, 40, 33, 31,  5, 12,  9, 37, 32, 41, 18, 15, 10,  5,  4,  5,
       40,  7, 41, 33,  4, 44, 23, 45, 43, 18, 28, 34, 44, 23, 16])

In [38]:
np.percentile(arr100,90)


45.0

In [4]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/insurance.csv")

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]